export AIRFLOW_HOME="/home/khalidabdelrazk/projects/workshops/ELT-DuckDB-using-DBT-and-Airflow/airflow_home"
export DBT_PROFILES_DIR="/home/khalidabdelrazk/projects/workshops/ELT-DuckDB-using-DBT-and-Airflow"
source "/home/khalidabdelrazk/projects/workshops/ELT-DuckDB-using-DBT-and-Airflow/.venv/bin/activate"
echo "--- Environment Activated ---"
echo "AIRFLOW_HOME: $AIRFLOW_HOME"
echo "DBT_PROFILES_DIR: $DBT_PROFILES_DIR"
echo "DUCKDB_PATH: /home/khalidabdelrazk/projects/workshops/ELT-DuckDB-using-DBT-and-Airflow/warehouse.duckdb"
